config/routes.rb
DiscoForum::Application.routes.draw do

  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]

  resources :themas do
    resources :topics, shallow: true do
      resources :posts, only: [:new, :create]
    end
  end

  get '/topics', to: 'topics#index'

  resources :posts, only: [:edit, :update, :destroy]

  resources :admin_messages

  resources :users do
    member do
      put 'ban'
      put 'unban'
    end
    collection do
      get 'verificated'
      get 'userpage'
      post 'logout'
      post 'login'
      get 'banned'
    end
  end

  resources :roles, only: [:edit, :update]


  
  get '/admins', to: 'home#admins'

  get 'event_source/:projection/:event' => 'event_source#projected', as: 'event_source'
  root to: 'home#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  self.table_name = 'topics'

  has_many :posts
  
  belongs_to :thema
  belongs_to :user
  
  def updatable_attributes
    attributes.slice(*%w(id title user_id thema_id))
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include EventSource
  before_action :set_thema, only: [:new, :create]
  before_action :authenticate, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_unbanned
  before_action :validate_user, only: [:edit, :update, :destroy]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(id_param)
  end

  def new
    @topic = CreateTopicCommand.new
  end

  def create
    @topic = CreateTopicCommand.new(topic_params.merge(thema_id: @thema.id, user_id: current_user.id))
    if store_event_id Domain.run_command(@topic)
      redirect_to  @topic, notice: 'Diskussion wurde erfolreich erstellt.' 
    else
      render 'new'
    end
  end

  def edit
    @topic = UpdateTopicCommand.new Topic.find(id_param).updatable_attributes
  end
  
  def update
    @topic = UpdateTopicCommand.new topic_params.merge(id: id_param, user_id: current_user.id)
    if store_event_id Domain.run_command(@topic)
      redirect_to @topic, notice: 'Diskussion wurde geändert.'
    else
      render 'edit'
    end
  end

  def destroy
    delete_topic = DeleteTopicCommand.new id: id_param
    if store_event_id Domain.run_command(delete_topic)
      redirect_to themas_path, notice: 'Diskussion wurde gelöscht.'
    else
      redirect_to themas_path, alert: 'Diskussion konnte nicht gelöscht werden.'
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end

  def id_param
    params.require(:id).to_i
  end

  def set_thema
    @thema = Thema.find(params[:thema_id])
  end

  def validate_user
    unless Topic.find(id_param).user_id == id_param || current_user.admin?
      flash[:error] = 'Sie haben nicht die benoetigten Rechte um diese Aktion durchzufuehren!'
      redirect_to themas_path(id: params[:thema_id])
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="well">
  <%= simple_form_for(shallow_args(@thema, @topic)) do |f| %>
    <% if @topic.errors.any? %>
      <div class="alert alert-error">
        <ul class="list-unstyled">
          <% @topic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.input :title, label: 'Titel', placeholder: 'Titel' %>
    <span class="pull-right">
      <%= link_to 'Abbrechen', :back || thema_path(:thema_id), class: 'btn btn-default' %>
      <%= f.submit 'Speichern', class: 'btn btn-danger' %>
    </span>
    <div class="clearfix" />

  <% end %>
</div>

app/views/topics/edit.html.erb
<div class="col-sm-6 col-xs-offset-3">
  <h1>Diskussion bearbeiten</h1>

  <%= render 'form' %>

</div>

app/views/topics/index.html.erb
<%= event_source('TopicProjection') %>
<h1>Topic-Übersicht</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Erstellt von</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.title, topic_path(id: topic.id) %></td>
        <td><%= topic.benutzername %></td>
        <td>
          <span class="pull-right">
            <%= link_to 'Bearbeiten', edit_topic_path(id: topic.id), class: 'btn btn-warning btn-xs' %>
            <%= link_to 'Löschen', topic, method: :delete, data: { confirm: 'Willst du das Topic wirklich löschen?' }, class: 'btn btn-danger btn-xs' %></td>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/topics/new.html.erb
<div class="col-sm-6 col-xs-offset-3">
  <h1>Neues Topic</h1>
  <%= render 'form' %>
</div>

app/views/topics/show.html.erb
<%= event_source('TopicProjection') %>

<p class="hint"><%= link_to 'Zurück zum Thema', thema_path(id: @topic.thema_id), class: 'btn btn-default' %></p>

<div class="jumbotron">
  <h1>
    <%= @topic.title %>
  </h1>

  <p>
    <strong>Ersteller:</strong>
    <%= @topic.benutzername %>
  </p>

  <p><%= link_to 'Verfolgen', new_subscription_path(topic_id: @topic.id), class: 'btn btn-primary' %></p>


</div>

<h2>Beiträge</h2>

<% if @topic.posts.empty? %>
  <p class="hint">Es wurden bisher noch keine Beiträge verfasst.</p>
<% else %>
  <ul class="list-unstyled">
    <% @topic.posts.each do |post| %>
    <%= render 'posts/single_post', post: post %>
    <% end %>
  </ul>
<% end %>


<p> 
  
  <%= link_to 'Beitrag hinzufügen', new_topic_post_path(topic_id: @topic.id), class: 'btn btn-primary btn-sm' %>
  <span class="pull-right">
    <%= link_to 'Diskussion bearbeiten', edit_topic_path(@topic), class: 'btn btn-warning btn-sm' %>
  </span>
  
</p>