config/routes.rb
DiscoForum::Application.routes.draw do

  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]

  resources :themas do
    resources :topics, shallow: true do
      resources :posts, only: [:new, :create]
    end
  end

  get '/topics', to: 'topics#index'

  resources :posts, only: [:edit, :update, :destroy]

  resources :admin_messages

  resources :users do
    member do
      put 'ban'
      put 'unban'
    end
    collection do
      get 'verificated'
      get 'userpage'
      post 'logout'
      post 'login'
      get 'banned'
    end
  end

  resources :roles, only: [:edit, :update]


  
  get '/admins', to: 'home#admins'

  get 'event_source/:projection/:event' => 'event_source#projected', as: 'event_source'
  root to: 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = 'users'
  has_many :last_posts
  has_many :admin_messages
  has_many :subscriptions
  
  def typ
    super || 0
  end
  
	def banned?
	  ban
	end
  
  def verificated?
    verificated
  end
  
  
  def authenticated?
    persisted?
  end
	def registered?
    authenticated? && !banned?
	end
	def admin?
    typ > 0 && !banned?
	end

  def superior?
    typ > 1 && !banned?
	end

	def self.guest
		new
	end
  
  def updatable_attributes
    attributes.slice(*%w(id name vorname email benutzername passwort))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include EventSource
  before_action :authenticate, only: [:userpage, :edit, :update, :show, :delete]
  before_action :require_admin, only: [:show, :delete, :ban]
  before_action :validate_user, only: [:edit, :update]

  def index
    @user = LogInCommand.new
  end

  def show
    @users = User.all
  end

  def new
  	@user = RegisterUserCommand.new
  end

  def edit
    @user = UpdateUserCommand.new User.find(id_param).updatable_attributes
  end

  def create
    @user = RegisterUserCommand.new user_params.merge(typ: 0, shash: SecureRandom.hex(10))
    if store_event_id Domain.run_command(@user)
      UserMailer.registermail(@user).deliver
      redirect_to({action: :index}, notice: 'Sie haben sich erfolgreich registriert.')
    
    else
      render 'new'
    end
  end

  def update
    @user = UpdateUserCommand.new user_params.merge(id: id_param)
    if store_event_id Domain.run_command(@user)
      redirect_to({action: :userpage}, notice: 'Daten erfolgreich geaendert')
    else
      render 'edit'
    end
  end

  def delete
    delete_user = DeleteUserCommand.new id: id_param
    if store_event_id Domain.run_command(delete_user)
      redirect_to({action: :index}, notice: 'Account erfolgreich gelöscht.')
    else
      redirect_to({action: :index}, alert: 'Account konnte nicht gelöscht werden.')
    end
  end

  #Sonstige Methoden

  def login
    login = LogInCommand.new login_params
    if store_event_id Domain.run_command(login)
      session[:user] = User.where(benutzername: login.benutzername).first.id
      if params[:merk].nil? || params[:merk] == users_path
        redirect_to userpage_user_path(id: session[:user])
      else
        redirect_to params[:merk]
      end
    else
      flash[:error] = 'Fehler: Falscher Benutzername und/oder falsches Passwort!'
      redirect_to users_path(merk: params[:merk])
    end
  end

  def userpage
  end
  
  def logout
    reset_session
    
    flash[:success] = 'Sie haben sich erfolgreich ausgeloggt!'
    redirect_to users_path
  end
  
  def ban
    ban = BanUserCommand.new(user_id: id_param)
    store_event_id Domain.run_command(ban)
    redirect_to user_path(id: 1), notice: "Der Nutzer mit der id #{id_param} wurde gesperrt!"
  end

  def unban
    unban = UnbanUserCommand.new(user_id: id_param)
    store_event_id Domain.run_command(unban)
    redirect_to user_path(id: 1), notice: "Der Nutzer mit der id #{id_param} wurde entsperrt!"
  end

  def banned

    if current_user.rate == 0
      @permitted = false
    else
      @permitted = true
      @admin_message = CreateAdminMessageCommand.new
    end
  end
  
  def verificated
    user = User.where(shash: params[:userunlock]).take
    verificated = VerificatedUserCommand.new(user_id: user.id)
    store_event_id Domain.run_command(verificated)
    redirect_to users_path, notice: "Sie wurden erfolgreich verifiziert!"
  end

private
  def regmail

  end

  def id_param
      params.require(:id).to_i
   end

  def validate_user
    if current_user.id != id_param && !current_user.admin? # && !(params[:userunlock] == URI.encode(Digest::MD5.hexdigest(@user.benutzername+Date.today.to_s+Time.now.strftime("%I").to_s)))
      redirect_to({action: :index}, notice: 'Sie haben nicht die benötigten Rechte, um diese Aktion durchzuführen!')
    end 
  end
  
  def user_params
    params.require(:user).permit(:vorname, :name, :email, :benutzername, :passwort)
  end

  def login_params
    params.require(:user).permit(:benutzername, :passwort)
  end
end

app/views/users/banned.html.erb
<h1>Ihr Benutzerkonto wurde gesperrt!</h1>
<% if @permitted %>
	<p>Ein Administrator war der Meinung, dass Sie es zu bunt getrieben haben. Sie haben die Möglichkeit, <b>eine</b> Nachricht an die Moderatoren zu schreiben, in der Sie ihr Fehlverhalten erklären können und um Freischaltung bitten können.</p>

	<%= render 'admin_messages/form' %>
<% else %>
	<p>Sie haben ihre Nachricht an einen Moderator bereits verfasst. Sollte dem noch etwas hinzuzufügen sein, müssen Sie einen Forum-Administrator per Mail kontaktieren</p>
<% end %>

app/views/users/edit.html.erb
<div class="col-sm-6 col-xs-offset-3">
  <h1>Nutzerdetails bearbeiten</h1>

  <div class="well">
    <%= simple_form_for(@user) do |f| %>
        <% if @user.errors.any? %>
            <div class="alert alert-error">
              <ul class="list-unstyled">
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <%= f.input :name, label: 'Name', placeholder: 'Name' %>
        <%= f.input :vorname, label: 'Vorname', placeholder: 'Vorname' %>
        <%= f.input :email, label: 'Email', placeholder: 'Email' %>
        <%= f.input :benutzername, label: 'Benutzername', placeholder: 'Benutzername' %>
        <%= f.input :passwort, as: :password, label: 'Passwort', placeholder: 'Passwort' %>


        <%= link_to 'Zurück zur Nutzerseite', userpage_users_path, class: 'btn btn-default' %>
        <span class="pull-right">
            <%= f.button :submit, class: 'btn btn-danger' %>
        </span>

        <div class="clearfix"/>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= event_source('UserProjection') %>
<div class="col-sm-6 col-xs-offset-3">
  <h1>Anmelden</h1>
  <div class="well">

    <%= simple_form_for(@user, url: login_users_path, method: :post) do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-error">
          <ul class="list-unstyled">
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :benutzername, label: 'Benutzername', placeholder: 'Benutzername' %>
      <%= f.input :passwort, label: 'Passwort', placeholder: 'Passwort', as: :password %>
      <%= hidden_field_tag( :merk, params[:merk]) %>
      <%= f.submit 'Anmelden', class: 'btn btn-danger pull-right' %>
      <div class="clearfix" />
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-sm-6 col-xs-offset-3">
  <h1>Registieren</h1>
  <div class="well">

    <%= simple_form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-error">
          <ul class="list-unstyled">
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.input :vorname, label: 'Vorname', placeholder: 'Vorname' %>
      <%= f.input :name, label: 'Name', placeholder: 'Name' %>
      <%= f.input :benutzername, label: 'Benutzername', placeholder: 'Benutzername' %>
      <%= f.input :email, label: 'Email', placeholder: 'Email', as: :email %>
      <%= f.input :passwort, label: 'Passwort', placeholder: 'Passwort', as: :password %>

      <%= f.submit 'Registrieren', class: 'btn btn-danger pull-right' %>
      <div class="clearfix" />
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= event_source('UserProjection') %>
<h1>Benutzerübersicht</h1><br>
<table class="table table-striped">
	<thead>
		<tr>
			<th width="5%">id</th>
			<th>Benutzername</th>
			<th>Name, Vorname</th>
			<th>Email</th>
      <th></th>
      <th></th>
      <th></th>
      <th>Rolle</th>
      <% if @current_user.superior? %>
      	<th></th>
      <% end %>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.id %></td>
				<td><%= user.benutzername %></td>
				<td><%= user.name %>, <%= user.vorname %></td>
				<td><%= user.email %></td>
				<td><%= link_to 'Bearbeiten', edit_user_path(user) %></td>
				<td><%= link_to 'Löschen', user, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
				<% if user.banned? %>
        <td><%= link_to 'Sperrung aufheben', unban_user_path(id: user.id), method: :put %></td>
				<% else %>
        <td><%= link_to 'Sperren', ban_user_path(id: user.id), method: :put %></td>
        <% end %>
        <% case user.typ %>
        	<% when 0 %>
        		<td>Nutzer</td>
        	<% when 1 %>
        		<td>Forum-Moderator</td>
        	<% when 2 %>
        		<td>Forum-Administrator</td>
        	<% else %>
        		<td>Typ unbekannt</td>
        	<% end %>
        <% if @current_user.superior? %>
        	<td><%= link_to "Typ ändern", edit_role_path(id: user.id) %></td>
        <% end %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/users/userpage.html.erb
<%= event_source('UserProjection') %>

<h1>
  <%= gravatar(@current_user.id, 100, 100) %> 
  <%= @current_user.benutzername %>
</h1>
<%= link_to 'Nutzerdetails bearbeiten', edit_user_path(current_user) %>

<h2>Aktuelle Beiträge</h2>

<table class="table table-striped">
  <thead>
  <tr>
    <th width="20%">Titel</th>
    <th width="60%">Inhalt</th>
    <th width="20%">Erstellt</th>
  </tr>
  </thead>
  <tbody>
  <% LastPost.for_user(current_user).each do |post| %>
   <tr>
     <td><%=post.title %></td>
     <td><%=post.text %></td>
     <td><%= l post.created_at, format: :short %></td>
  <% end %>
  </tbody>
</table>



<h2>Aktivitäten in verfolgten Diskussionen</h2>
<% current_user.subscriptions.each do |subscription| %>
    <h3>
      <%= link_to subscription.topic_name, topic_path(id: subscription.topic_id) %>
      <%= link_to "Einstellungen...", edit_subscription_path(id: subscription.id), class: 'btn btn-default btn-xs' %>
      <%= link_to 'Verfolgen beenden', subscription, method: :delete, class: 'btn btn-danger btn-xs' %>
    </h3>

    <% if subscription.subscribedposts.empty? %>
      <p class="hint">Es wurden bisher noch keine Beiträge verfasst.</p>
    <% else %>
      <ul class="list-unstyled">
        <% subscription.subscribedposts.each do |post| %>
        <li class="post">
          <div class="user">
            <%= gravatar(post.subscription.user_id, 40, 40) %><br/>
            <%= post.benutzername %>
          </div>
          <div class="content">
            <div class="title"><%= post.title %></div>
            <div class="body"><%= post.text %></div>
            <div class="footer">
              Am <%= l post.created_at, format: :short %> von <%= post.benutzername %>
            </div>
          </div>
          <div class="clearfix"></div>
        </li>
        <% end %>
      </ul>
    <% end %>
<% end %>

<% if current_user.admin? %>
 <h2>
  Adminbereich
  <%= link_to 'Userübersicht', user_path(id: 1), class: 'btn btn-default btn-xs' %>
  <%= link_to 'Topicübersicht', thema_topics_path(thema_id: 1), class: 'btn btn-default btn-xs' %>
 </h2>
 
 
 <h4>Aktuelle Nutzeranfragen</h4>

 <table class="table table-striped">
   <thead>
   <tr>
     
     <th>Nutzer</th>
     <th width="90%">Message</th>
   </tr>
   </thead>
   <tbody>
   <% AdminMessage.for_user(current_user).each do |amessage| %>
    <tr>
      <td><%= amessage.message %></td>
      <td><%= amessage.user.benutzername %></td>
    </tr>
   <% end %>
   </tbody>
 </table>

<% end %>