config/routes.rb
DiscoForum::Application.routes.draw do

  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]

  resources :themas do
    resources :topics, shallow: true do
      resources :posts, only: [:new, :create]
    end
  end

  get '/topics', to: 'topics#index'

  resources :posts, only: [:edit, :update, :destroy]

  resources :admin_messages

  resources :users do
    member do
      put 'ban'
      put 'unban'
    end
    collection do
      get 'verificated'
      get 'userpage'
      post 'logout'
      post 'login'
      get 'banned'
    end
  end

  resources :roles, only: [:edit, :update]


  
  get '/admins', to: 'home#admins'

  get 'event_source/:projection/:event' => 'event_source#projected', as: 'event_source'
  root to: 'home#index'
end

app/models/thema.rb
class Thema < ActiveRecord::Base
  self.table_name = 'themas'
  
  has_many :unterthemen, foreign_key: :belong, class_name: "Thema"
  belongs_to :oberthema, foreign_key: :belong, class_name: "Thema"
  has_many :topics

  def self.hauptindex
    where(belong: nil)
  end

  def self.unterthemen(thema_id)
    where(belong: thema_id)
  end

  def updatable_attributes
    attributes.slice(*%w(id title description belong))
  end
end

app/controllers/themas_controller.rb
class ThemasController < ApplicationController
  include EventSource
  before_action :authenticate, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @themas = Thema.hauptindex
  end

  def show
    @thema = Thema.find(id_param)
  end

  def new
    @thema = CreateThemaCommand.new(belong: params[:belong])
  end

  def edit
    @thema = UpdateThemaCommand.new Thema.find(id_param).updatable_attributes
  end

  def create
    @thema = CreateThemaCommand.new thema_params
    if store_event_id Domain.run_command(@thema)
      redirect_to @thema, notice: 'Thema wurde erstellt.'
    else
      render 'new'
    end
  end

  def update
    @thema = UpdateThemaCommand.new thema_params.merge(id: id_param)
    if store_event_id Domain.run_command(@thema)
      redirect_to @thema, notice: 'Thema wurde aktualisiert.'
    else
      render 'edit'
    end
  end

  def destroy
    delete_thema = DeleteThemaCommand.new id: id_param
    if store_event_id Domain.run_command(delete_thema)
      redirect_to({action: :index}, notice: 'Thema wurde gelöscht.')
    else
      redirect_to thema_url(id: id_param), alert: 'Thema konnte nicht gelöscht werden!'
    end
  end

  private

  def thema_params
    params.require(:thema).permit(:title,:description,:belong)
  end

  def id_param
    params.require(:id).to_i
  end
end

app/helpers/themas_helper.rb
module ThemasHelper
end

app/views/themas/_form.html.erb
<div class="well">
  <%= simple_form_for(@thema) do |f| %>
    <% if @thema.errors.any? %>
      <div class="alert alert-error">
        <ul class="list-unstyled">
          <% @thema.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.input :title, label: 'Titel', placeholder: 'Titel' %>
    <%= f.input :description, label: 'Beschreibung', as: :text %>
    
    <%= f.input :belong, collection: Thema.all, label_method: :title, value_method: :id, label: "Thema", include_blank: 'Wurzel' %>


    <span class="pull-right">
      <%= link_to 'Abbrechen', :back || thema_path(:thema_id), class: 'btn btn-default' %>
      <%= f.submit 'Speichern', class: 'btn btn-danger' %>
    </span>
    <div class="clearfix" />

  <% end %>
</div>

app/views/themas/edit.html.erb
<div class="col-sm-6 col-xs-offset-3">
  <h1>Thema bearbeiten</h1>

  <%= render 'form' %>
</div>

app/views/themas/index.html.erb
<%= event_source('ThemaProjection') %>
<h1>Themenübersicht</h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Titel</th>
      <th>Beschreibung</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @themas.each do |thema| %>
      <tr>
        <td><%= link_to thema.title, thema %></td>
        <td><%= thema.description %></td>
        <td><%= link_to 'Bearbeiten', edit_thema_path(thema), class: 'btn btn-warning btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Zurück zur Startseite', root_url, class: 'btn btn-default btn-sm' %>
<%= link_to 'Neues Thema', new_thema_path(belong_id: 0), class: 'btn btn-primary btn-sm' if current_user.admin? %>

app/views/themas/new.html.erb
<div class="col-sm-6 col-xs-offset-3">
  <h1>Neues Thema</h1>

  <%= render 'form' %>
</div>

app/views/themas/show.html.erb
<%= event_source('ThemaProjection') %>
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1>
    <%= @thema.title %>
    <%= link_to 'Bearbeiten', edit_thema_path(@thema), class: 'btn btn-warning btn-sm' if current_user.admin? %>
  </h1>

  <p><%= @thema.description %></p>

</div>


<article id="unterthemen">
<h2>
  Unterthemen
  <%= link_to 'Unterthema hinzufügen', new_thema_path(belong: @thema.id), class: 'btn btn-link' if current_user.admin? %>
</h2>

<% unless @thema.unterthemen.empty? %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Titel</th>
      <th>Beschreibung</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @thema.unterthemen.each do |thema| %>
      <tr>
        <td><%= link_to thema.title, thema %></td>
        <td><%= thema.description %></td>
        <td>
          <span class="pull-right">
          <%= link_to 'Bearbeiten', edit_thema_path(thema), class: 'btn btn-warning btn-xs' %>
          <%= link_to 'Löschen', thema, method: :delete, data: { confirm: 'Willst du das Unterthema wirklich löschen?' }, class: 'btn btn-danger btn-xs' %></td>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
<% end %>
</article>

<article id="topics">
  <h2>
    Zugehörige Diskussionen
    <%= link_to 'Diskussion starten', new_thema_topic_path(thema_id: @thema.id), class: 'btn btn-link' %>
  </h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Diskussion</th>
        <th>Benutzer</th>
        <th>Posts</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @thema.topics.each do |topic| %>
        <tr>
          <td><%= link_to 'Verfolgen', new_subscription_path(topic_id: topic.id), class: 'btn btn-primary btn-xs' %></td>
          <td><strong><%= link_to topic.title, topic_path(topic) %></strong></td>
          
          <% unless User.where(id: topic.user_id).empty? %>
            <td><%= gravatar(topic.user_id) %> <%= topic.user.benutzername %></td>
          <% else %>
            <td>Gelösche Person</td>
          <% end %>

          <td><%= topic.count %></td>
          
          <td>
            <span class="pull-right">
              <%= link_to 'Bearbeiten', edit_topic_path(topic), class: 'btn btn-warning btn-xs' %>
              <%= link_to 'Löschen', topic, method: :delete, data: { confirm: 'Willst du die Diskussion wirklich löschen?' }, class: 'btn btn-danger btn-xs' %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</article>

<% if @thema.belong.nil? %>
  <%=link_to 'Zurück zur Übersicht', themas_path, class: 'btn btn-default' %>
<% else %>
  <%= link_to 'Zurück', thema_path(id: @thema.belong), class: 'btn btn-default' %>
<% end %>