config/routes.rb
DiscoForum::Application.routes.draw do

  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]

  resources :themas do
    resources :topics, shallow: true do
      resources :posts, only: [:new, :create]
    end
  end

  get '/topics', to: 'topics#index'

  resources :posts, only: [:edit, :update, :destroy]

  resources :admin_messages

  resources :users do
    member do
      put 'ban'
      put 'unban'
    end
    collection do
      get 'verificated'
      get 'userpage'
      post 'logout'
      post 'login'
      get 'banned'
    end
  end

  resources :roles, only: [:edit, :update]


  
  get '/admins', to: 'home#admins'

  get 'event_source/:projection/:event' => 'event_source#projected', as: 'event_source'
  root to: 'home#index'
end

app/models/admin_message.rb
class AdminMessage < ActiveRecord::Base
  self.table_name = 'admin_messages'
  belongs_to :user

  def self.for_user(user)
    if user.admin?
      all
    else
      user.admin_messages
    end
  end

  def updatable_attributes
    { message: message, id: id }
  end
end

app/models/last_post.rb
class LastPost < ActiveRecord::Base
  self.table_name = 'last_posts'
  belongs_to :user
  has_many :posts

  def self.for_user(user)
    where(user_id: user.id).order(created_at: :desc)
  end
end

app/models/latest_topic.rb
class LatestTopic < ActiveRecord::Base
  self.table_name = 'latest_topics'
  has_many :posts
  
  belongs_to :thema
  belongs_to :user
end

app/models/latesttopics.rb
class Latesttopics < ActiveRecord::Base
  self.table_name = 'latesttopics'
  has_many :posts
  
  belongs_to :thema
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  self.table_name = 'posts'
  
  belongs_to :topic
  
  def self.from_user(user_id)
    where(user_id: user_id)
  end
  
  def self.posted_since(time = 1.minute.ago)
    where(arel_table[:created_at].gt time)
  end

  def updatable_attributes
    attributes.slice(*%w(id title text user_id topic_id))
  end
end

app/models/subscribedpost.rb
class Subscribedpost < ActiveRecord::Base
  self.table_name = 'subscribedposts'
  belongs_to :subscription
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  self.table_name = 'subscriptions'
  belongs_to :user
  has_many :subscribedposts

  def updatable_attributes
    attributes.slice(*%w(id email topic_id))
  end
end

app/models/thema.rb
class Thema < ActiveRecord::Base
  self.table_name = 'themas'
  
  has_many :unterthemen, foreign_key: :belong, class_name: "Thema"
  belongs_to :oberthema, foreign_key: :belong, class_name: "Thema"
  has_many :topics

  def self.hauptindex
    where(belong: nil)
  end

  def self.unterthemen(thema_id)
    where(belong: thema_id)
  end

  def updatable_attributes
    attributes.slice(*%w(id title description belong))
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  self.table_name = 'topics'

  has_many :posts
  
  belongs_to :thema
  belongs_to :user
  
  def updatable_attributes
    attributes.slice(*%w(id title user_id thema_id))
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = 'users'
  has_many :last_posts
  has_many :admin_messages
  has_many :subscriptions
  
  def typ
    super || 0
  end
  
	def banned?
	  ban
	end
  
  def verificated?
    verificated
  end
  
  
  def authenticated?
    persisted?
  end
	def registered?
    authenticated? && !banned?
	end
	def admin?
    typ > 0 && !banned?
	end

  def superior?
    typ > 1 && !banned?
	end

	def self.guest
		new
	end
  
  def updatable_attributes
    attributes.slice(*%w(id name vorname email benutzername passwort))
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @latest_topics = LatestTopic.all
  end

  def verificated
    verificated = VerificatedUserCommand.new(user_id: params[:id])
    Domain.run_command(verificated)
    flash[:success] = "Der Nutzer mit der ID #{params[:id]} wurde erfolgreich verifiziert!"
    redirect_to user_path(id: 1)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include EventSource
  before_action :authenticate, only: [:create, :new, :edit, :update, :destroy]

  def new
    @topic = Topic.find(params[:topic_id])
    @post = CreatePostCommand.new(topic_id: @topic.id)
  end

  def edit
    @post = UpdatePostCommand.new(Post.find(id_param).updatable_attributes)
  end

  def create
    @post = CreatePostCommand.new(post_params.merge(user_id: session[:user]))
    if store_event_id Domain.run_command(@post)
      redirect_to topic_path(id: @post.topic_id), notice: 'Post wurde erstellt.'
    else
      render 'new'
    end
  end

  def update
    @post = UpdatePostCommand.new(post_params.merge(id: id_param, user_id: session[:user]))
    if store_event_id Domain.run_command(@post)
      redirect_to topic_path(id: @post.topic_id), notice: 'Post wurde geändert.'
    else
      render 'edit'
    end
  end

  def destroy
    topic_id = Post.find(id_param).topic_id
    delete_post = DeletePostCommand.new(id: id_param, topic_id: topic_id)
    if store_event_id Domain.run_command(delete_post)
      redirect_to topic_path(id: topic_id), notice: 'Post wurde geloescht.'
    else
      redirect_to topic_path(id: topic_id), alert: 'Post konnte nicht geloescht werden!'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :topic_id)
  end

  def id_param
    params.require(:id).to_i
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  include EventSource
  before_action :authenticate
  before_action :require_superior
  before_action :fetch_user
  
  def edit
    @role = ChangeRoleCommand.new(user_id: @user.id, typ: @user.typ)
  end

  def update
  	@role = ChangeRoleCommand.new(role_params.merge(user_id: @user.id))
		if store_event_id Domain.run_command(@role)
			redirect_to @user, notice: "Typ erfolgreich geändert"
    else
      render 'edit'
		end
	end

  private

  def role_params
    params.require(:role).permit(:typ)
  end

  def fetch_user
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def shallow_args(parent, child)
    child.try(:persisted?) ? child : [parent, child]
	end
end

app/helpers/event_source_helper.rb
module EventSourceHelper
  def event_source(projection)
    ActiveEvent::EventSourceServer.projection_status(projection)
    event_id = read_and_clear_event_id
    if event_id
      content_tag(:div, '',
                  class: 'event-source',
                  data: {href: event_source_path(projection: projection, event: event_id)})
    end
  end
end

app/helpers/gravatar_helper.rb
module GravatarHelper
  
  def user_gravatar(gravatar_id, width=50, height=50)
    image_tag("http://www.gravatar.com/avatar/#{gravatar_id}", width: width, height: height)
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def usertest

    if session[:user].nil?
      if params[:merk].nil? && params[:merk] != users_path
        merke = request.original_url
      else
        merke = params[:merk]
      end
      link_to 'Log in!', users_path(merk: merke)
    else
      (link_to 'Logout', logout_users_path, method: :post)
      
    end
  end
  def username
    user = User.find(session[:user])
    if user.present?
      "Angemeldet als #{user.benutzername}"
    end  
  end

  def userpage
    link_to 'Userpage', userpage_users_path
  end 

  def gravatar(user_id, width=20, height=20)
    require 'digest/md5'
    email_address = User.find(user_id).email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    image_src = "http://www.gravatar.com/avatar/#{hash}"
    image_tag(image_src, width: width, height: height)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/themas_helper.rb
module ThemasHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
 
   <% flash.each do |key, message| -%>
    <%= content_tag :div, message, class: "alert alert-#{key}" %>
   <% end -%>
<% end -%>

app/views/layouts/_login.html.erb
<div class="login ">
<%= usertest %>
<%= username %>
<%= userpage %>
<%= gravatar %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Disco-Forum</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Disco Forum', root_url, class: 'navbar-brand' %>
        </div>

        <ul class="nav navbar-nav">
          <li><%= link_to 'Themen', themas_path %></li>
          <li><%= link_to 'Admin Nachrichten', admin_messages_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if session[:user].present? %>
            <li>
              <p class="nav navbar-text"><%= username %></p>
            </li>
          
            <li><%= userpage %></li>
            <li><p class="nav navbar-text"><%= gravatar(session[:user]) %></p></li>
          <% else %>
            <li><%= link_to 'Registrieren', new_user_path %></li>
          <% end %>
            <li><%= usertest %></li>
        </ul>
      </div>
    </nav>
 
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
</body>
</html>

app/views/roles/edit.html.erb
<div class="col-sm-6 col-xs-offset-3">
  <h1>Rolle des Nutzers ändern</h1>

  <div class="well">
    <%= simple_form_for(@role) do |f| %>
        <%= f.input :typ do %>
            <%= f.collection_radio_buttons(:typ, [[0, 'Normaler Nutzer'] ,[1, 'Forum-Moderator'], [2, 'Administrator']], :first, :last, item_wrapper_tag: :div, item_wrapper_class: :radio) { |b| b.radio_button + b.label } %>
        <% end %>

        <div class="pull-right clearfix">
          <%= f.submit "Änderungen speichern", class: 'btn btn-danger' %>
          <%= link_to "Zurück zur Nutzerübersicht", user_path(id: 1), class: 'btn btn-default' %>
        </div>
        <div class="clearfix"></div>
    <% end %>
  </div>
</div>